Trait {
	#name : 'TPyramidProjectModelObserver',
	#category : 'Pyramid-models',
	#package : 'Pyramid',
	#tag : 'models'
}

{ #category : 'as yet unclassified' }
TPyramidProjectModelObserver >> pyramidElementsChanged [

	
]

{ #category : 'as yet unclassified' }
TPyramidProjectModelObserver >> pyramidFirstLevelElementsChanged [

	
]

{ #category : 'as yet unclassified' }
TPyramidProjectModelObserver >> pyramidSelectionChanged [
]
