Trait {
	#name : #TPyramidPipelineObserver,
	#instVars : [
		'pipeline'
	],
	#category : #'Pyramid-commands'
}

{ #category : #'as yet unclassified' }
TPyramidPipelineObserver >> pyramidPipelineCancelCommand [
]

{ #category : #'as yet unclassified' }
TPyramidPipelineObserver >> pyramidPipelineExecuteCommand [

]

{ #category : #'as yet unclassified' }
TPyramidPipelineObserver >> pyramidPipelineTerminateCommand [

]

{ #category : #'as yet unclassified' }
TPyramidPipelineObserver >> pyramidPipelineVerifyCommand [

]
