Class {
	#name : #PyramidFakePluginA,
	#superclass : #Object,
	#traits : 'TPyramidPlugin',
	#classTraits : 'TPyramidPlugin classTrait',
	#category : #'Pyramid-Tests-cases-core'
}

{ #category : #'meta-data' }
PyramidFakePluginA class >> dependencies [
	"Put symbol as the class name for each dependencies."

	^ {  }
]

{ #category : #initialization }
PyramidFakePluginA class >> initialize [

	<script>

]
