Class {
	#name : #PyramidPropertiesManagerForTest,
	#superclass : #PyramidPropertiesManager,
	#instVars : [
		'presenterBuilder'
	],
	#category : #'Pyramid-Tests-cases-property'
}

{ #category : #'as yet unclassified' }
PyramidPropertiesManagerForTest >> presenterBuilder [

	^ presenterBuilder
]

{ #category : #accessing }
PyramidPropertiesManagerForTest >> presenterBuilder: anObject [ 
	presenterBuilder:=anObject
]
