Class {
	#name : #NeoPyramidInputPresenter,
	#superclass : #SpPresenter,
	#category : #'NeoPyramid-property'
}

{ #category : #'as yet unclassified' }
NeoPyramidInputPresenter >> emptyValue [
]

{ #category : #'as yet unclassified' }
NeoPyramidInputPresenter >> mixedValues [

	
]

{ #category : #'as yet unclassified' }
NeoPyramidInputPresenter >> value [

	
]

{ #category : #'as yet unclassified' }
NeoPyramidInputPresenter >> value: anObject [
]

{ #category : #'as yet unclassified' }
NeoPyramidInputPresenter >> whenValueChangedDo: aBlock [
]
