Class {
	#name : #PyramidBackgroundInputModel,
	#superclass : #Object,
	#instVars : [
		'page',
		'presenter'
	],
	#category : #'NeoPyramid-specs-custom'
}

{ #category : #accessing }
PyramidBackgroundInputModel >> page [

	^ page
]

{ #category : #accessing }
PyramidBackgroundInputModel >> page: anObject [

	page := anObject
]

{ #category : #accessing }
PyramidBackgroundInputModel >> presenter [

	^ presenter
]

{ #category : #accessing }
PyramidBackgroundInputModel >> presenter: anObject [

	presenter := anObject
]
