Trait {
	#name : #TPyramidActiveProjectModelObserver,
	#category : #'NeoPyramid-models'
}

{ #category : #'as yet unclassified' }
TPyramidActiveProjectModelObserver >> pyramidActiveProjectChangedChanged [

	
]

{ #category : #'as yet unclassified' }
TPyramidActiveProjectModelObserver >> pyramidRootsChangedOnActiveProject [
]

{ #category : #'as yet unclassified' }
TPyramidActiveProjectModelObserver >> pyramidSelectionChangedOnActiveProject [
]
