Trait {
	#name : #TPyramidActiveProjectModelObserver,
	#instVars : [
		'isLock'
	],
	#category : #'NeoPyramid-models'
}

{ #category : #'as yet unclassified' }
TPyramidActiveProjectModelObserver >> pyramidActiveProjectChanged [

	
]

{ #category : #'as yet unclassified' }
TPyramidActiveProjectModelObserver >> pyramidRootsChangedOnActiveProject [
]

{ #category : #'as yet unclassified' }
TPyramidActiveProjectModelObserver >> pyramidSelectionChangedOnActiveProject [
]
