Extension { #name : 'BlVisibility' }

{ #category : '*Pyramid-Bloc' }
BlVisibility >> asIcon [
"return a 16 by 16 `Form`"
	^ self shouldBeImplemented 
]

{ #category : '*Pyramid-Bloc' }
BlVisibility >> asString [
	"return a String"

	^ self shouldBeImplemented
]

{ #category : '*Pyramid-Bloc' }
BlVisibility >> nextVisibilityForTree [
"return the next visibility.
Visible -> Hidden -> Gone -> Visible"
	^ self shouldBeImplemented
]

{ #category : '*Pyramid-Bloc' }
BlVisibility >> setVisibilityOn: aPyramidVisibilityInputPresenter [

	self shouldBeImplemented
]
