Class {
	#name : #PyramidFakeConstraintsNoValue,
	#superclass : #Object,
	#category : #'Pyramid-Bloc-custom-specs-constraints'
}

{ #category : #factory }
PyramidFakeConstraintsNoValue >> horizontal [

	^ self
]

{ #category : #'as yet unclassified' }
PyramidFakeConstraintsNoValue >> pyramidSelectConstraintsOn: aPyramidConstraintsPresenter [
	
]

{ #category : #factory }
PyramidFakeConstraintsNoValue >> vertical [

	^ self 
]
