Class {
	#name : #PyramidSpacePluginExtension,
	#superclass : #Object,
	#classTraits : 'TPyramidPlugin classTrait',
	#category : #'Pyramid-Bloc-plugin-space'
}

{ #category : #adding }
PyramidSpacePluginExtension >> addPanelsOn: aPyramidSimpleWindow [

	.
]

{ #category : #actions }
PyramidSpacePluginExtension >> configureBuilder: aPyramidBuilder [

	.
]

{ #category : #'as yet unclassified' }
PyramidSpacePluginExtension >> connectOn: aPyramidEditor [

	.
]

{ #category : #'as yet unclassified' }
PyramidSpacePluginExtension >> installOnSpacePlugin: aSpacePlugin [
]
