Trait {
	#name : #TPyramidOpenFromSpacePluginExtension,
	#category : #'Pyramid-Bloc-plugin-edit-on-running'
}

{ #category : #'as yet unclassified' }
TPyramidOpenFromSpacePluginExtension >> configureCloseOnSpace: aSpace [
	"Do something with the space when you close the editor"

	
]

{ #category : #'as yet unclassified' }
TPyramidOpenFromSpacePluginExtension >> configureOpenFromSpace: aSpace [
	"Do something with the space when you open the editor"

	
]
